In [1]:
from google.colab import files
uploaded = files.upload()

Saving Mumbai_property_details.csv to Mumbai_property_details.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Mumbai_property_details.csv' , encoding='cp1252')

In [4]:
df.shape

(23405, 18)

In [5]:
df.head()

,Title,Price,Area,BHK,Bathrooms,Furnished,Balconies,Floor,Ownership,Facing,Amenities,Transaction Type,Property Type,Location,Year of Construction,Is Luxury,Description,Property Image
0,1BHK Multistorey Apartment for Rent in Bandra ...,"70,000",750 12800,1,1,Furnished,NaN,7,NaN,South -West,Main Road,Rent,Apartment,Mumbai,2012.0,F,"1 BHK, Multistorey Apartment is available for ...",67249079_2_PropertyImage345-4855396928822.jpg
1,3BHK Multistorey Apartment for Rent in Lodha N...,1.4 Lac,1980 12800,3,4,Unfurnished,4,21,NaN,East,"Garden/Park, Pool, Main Road",Rent,Apartment,Mumbai,1994.0,F,"3 BHK, Multistorey Apartment is available for ...",66155783_5_hatsAppImage20230217at13.56.28.jpeg
2,3BHK Multistorey Apartment for Rent in Lodha P...,1.9 Lac,1592 12800,3,3,Unfurnished,1,20,NaN,North - East,Main Road,Rent,Apartment,Mumbai,NaN,F,"3 BHK, Multistorey Apartment is available for ...",66686709_1_HOTO20230407165614.jpg
3,3BHK Multistorey Apartment for Rent in Rustomj...,1.1 Lac,1305 12800,3,3,Unfurnished,3,11,Freehold,West,"Garden/Park, Main Road",Rent,Apartment,Mumbai,2010.0,F,"3 BHK, Multistorey Apartment is available for ...",67875387_1_PropertyImage559-8385323621333.jpg
4,3BHK Multistorey Apartment for Rent in DLH The...,1.4 Lac,1350 12800,3,3,Unfurnished,NaN,29,Freehold,East,"Pool, Garden/Park, Main Road",Rent,Apartment,Mumbai,2000.0,F,"3 BHK, Multistorey Apartment is available for ...",66670931_3_PropertyImage314-6685675359874.jpg

In [6]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23405 entries, 0 to 23404
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Title                 23405 non-null  object
 1   Price                 23403 non-null  object
 2   Area                  23405 non-null  object
 3   BHK                   22994 non-null  object
 4   Bathrooms             23201 non-null  object
 5   Furnished             23216 non-null  object
 6   Balconies             10388 non-null  object
 7   Floor                 22285 non-null  object
 8   Ownership             2835 non-null   object
 9   Facing                19124 non-null  object
 10  Amenities             18092 non-null  object
 11  Transaction Type      23398 non-null  object
 12  Property Type         23405 non-null  object
 13  Location              23405 non-null  object
 14  Year of Construction  14885 non-null  float64
 15  Is Luxury             23403 non-null  object
 16  Description           23405 non-null  object
 17  Property Image        19607 non-null  object
dtypes: float64(1), object(17)
memory usage: 3.2+ MB

In [7]:
df.isnull().sum()

Title                       0
Price                       2
Area                        0
BHK                       411
Bathrooms                 204
Furnished                 189
Balconies               13017
Floor                    1120
Ownership               20570
Facing                   4281
Amenities                5313
Transaction Type            7
Property Type               0
Location                    0
Year of Construction     8520
Is Luxury                   2
Description                 0
Property Image           3798
dtype: int64

In [8]:
df.drop(columns=['Ownership','Property Image','Is Luxury'])

,Title,Price,Area,BHK,Bathrooms,Furnished,Balconies,Floor,Facing,Amenities,Transaction Type,Property Type,Location,Year of Construction,Description
0,1BHK Multistorey Apartment for Rent in Bandra ...,"70,000",750 12800,1,1,Furnished,NaN,7,South -West,Main Road,Rent,Apartment,Mumbai,2012.0,"1 BHK, Multistorey Apartment is available for ..."
1,3BHK Multistorey Apartment for Rent in Lodha N...,1.4 Lac,1980 12800,3,4,Unfurnished,4,21,East,"Garden/Park, Pool, Main Road",Rent,Apartment,Mumbai,1994.0,"3 BHK, Multistorey Apartment is available for ..."
2,3BHK Multistorey Apartment for Rent in Lodha P...,1.9 Lac,1592 12800,3,3,Unfurnished,1,20,North - East,Main Road,Rent,Apartment,Mumbai,NaN,"3 BHK, Multistorey Apartment is available for ..."
3,3BHK Multistorey Apartment for Rent in Rustomj...,1.1 Lac,1305 12800,3,3,Unfurnished,3,11,West,"Garden/Park, Main Road",Rent,Apartment,Mumbai,2010.0,"3 BHK, Multistorey Apartment is available for ..."
4,3BHK Multistorey Apartment for Rent in DLH The...,1.4 Lac,1350 12800,3,3,Unfurnished,NaN,29,East,"Pool, Garden/Park, Main Road",Rent,Apartment,Mumbai,2000.0,"3 BHK, Multistorey Apartment is available for ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23400,1BHK Multistorey Apartment for Rent in Goregao...,60 Lac,500 12800,1,1,Semi-Furnished,NaN,8,NaN,NaN,Rent,Apartment,Mumbai,NaN,"1 BHK, Multistorey Apartment is available for ..."
23401,1BHK Multistorey Apartment for Rent in Andheri...,25 Lac,None,1,1,Unfurnished,NaN,1,NaN,NaN,Rent,Apartment,Mumbai,NaN,"1 BHK, Multistorey Apartment is available for ..."
23402,1BHK Multistorey Apartment for Rent in,"7,000",None,1,1,Semi-Furnished,NaN,2,NaN,NaN,Rent,Apartment,Mumbai,NaN,"1 BHK, Multistorey Apartment is available for ..."
23403,2BHK Multistorey Apartment for Rent in,1 Lac,25 12800,2,NaN,NaN,NaN,NaN,NaN,NaN,Rent,Apartment,Mumbai,NaN,"2 BHK, Multistorey Apartment is available for ..."
23404,2BHK Multistorey Apartment for Rent in,1 Lac,25 12800,2,NaN,NaN,NaN,NaN,NaN,NaN,Rent,Apartment,Mumbai,NaN,"2 BHK, Multistorey Apartment is available for ..."

In [9]:
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

Duplicate rows: 3111

In [10]:
print(df['Transaction Type'].value_counts())
print(df['Property Type'].value_counts())
print(df['Furnished'].value_counts())

Transaction Type
Rent    23398
Name: count, dtype: int64
Property Type
Apartment                  22026
Residential House            746
Studio Apartment             261
Builder Floor Apartment      232
Villa                        107
Penthouse                     29
Service Apartment              4
Name: count, dtype: int64
Furnished
Semi-Furnished    9851
Unfurnished       7281
Furnished         6084
Name: count, dtype: int64

In [11]:
df.drop(columns=['Transaction Type','Location'])

,Title,Price,Area,BHK,Bathrooms,Furnished,Balconies,Floor,Ownership,Facing,Amenities,Property Type,Year of Construction,Is Luxury,Description,Property Image
0,1BHK Multistorey Apartment for Rent in Bandra ...,"70,000",750 12800,1,1,Furnished,NaN,7,NaN,South -West,Main Road,Apartment,2012.0,F,"1 BHK, Multistorey Apartment is available for ...",67249079_2_PropertyImage345-4855396928822.jpg
1,3BHK Multistorey Apartment for Rent in Lodha N...,1.4 Lac,1980 12800,3,4,Unfurnished,4,21,NaN,East,"Garden/Park, Pool, Main Road",Apartment,1994.0,F,"3 BHK, Multistorey Apartment is available for ...",66155783_5_hatsAppImage20230217at13.56.28.jpeg
2,3BHK Multistorey Apartment for Rent in Lodha P...,1.9 Lac,1592 12800,3,3,Unfurnished,1,20,NaN,North - East,Main Road,Apartment,NaN,F,"3 BHK, Multistorey Apartment is available for ...",66686709_1_HOTO20230407165614.jpg
3,3BHK Multistorey Apartment for Rent in Rustomj...,1.1 Lac,1305 12800,3,3,Unfurnished,3,11,Freehold,West,"Garden/Park, Main Road",Apartment,2010.0,F,"3 BHK, Multistorey Apartment is available for ...",67875387_1_PropertyImage559-8385323621333.jpg
4,3BHK Multistorey Apartment for Rent in DLH The...,1.4 Lac,1350 12800,3,3,Unfurnished,NaN,29,Freehold,East,"Pool, Garden/Park, Main Road",Apartment,2000.0,F,"3 BHK, Multistorey Apartment is available for ...",66670931_3_PropertyImage314-6685675359874.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23400,1BHK Multistorey Apartment for Rent in Goregao...,60 Lac,500 12800,1,1,Semi-Furnished,NaN,8,NaN,NaN,NaN,Apartment,NaN,F,"1 BHK, Multistorey Apartment is available for ...",NaN
23401,1BHK Multistorey Apartment for Rent in Andheri...,25 Lac,None,1,1,Unfurnished,NaN,1,NaN,NaN,NaN,Apartment,NaN,F,"1 BHK, Multistorey Apartment is available for ...",51543641_4_PropertyImage230-93973347098495.jpg
23402,1BHK Multistorey Apartment for Rent in,"7,000",None,1,1,Semi-Furnished,NaN,2,NaN,NaN,NaN,Apartment,NaN,F,"1 BHK, Multistorey Apartment is available for ...",NaN
23403,2BHK Multistorey Apartment for Rent in,1 Lac,25 12800,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,NaN,F,"2 BHK, Multistorey Apartment is available for ...",NaN
23404,2BHK Multistorey Apartment for Rent in,1 Lac,25 12800,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,NaN,F,"2 BHK, Multistorey Apartment is available for ...",NaN

In [12]:
df['Location'].value_counts()

Location
Mumbai    23405
Name: count, dtype: int64

In [13]:
df = df.drop(columns=[
    'Ownership',
    'Property Image',
    'Is Luxury',
    'Transaction Type',
    'Location'
])

In [14]:
df.shape

(23405, 13)

In [15]:
df['Price'].sample(30)

6321            1.2 Lac
21034             2 Lac
22725            60,000
1930             25,000
310              32,000
23025             8,000
11011            40,000
14852            30,000
11995           1.4 Lac
13030            10 Lac
6492             85,000
18767           4.8 Lac
15664           1.3 Lac
13224            40,000
9449             75,000
4747            2.7 Lac
3432             65,000
10710            55,000
8323              2 Lac
7995            2.8 Lac
18357            21,000
6155            2.3 Lac
23371    Call for Price
2247             16,500
12101            48,000
20879            98,000
17335            62,000
6236             45,000
12387            59,000
11083            50,000
Name: Price, dtype: object

In [16]:
import pandas as pd
import numpy as np

def clean_price(price):
    if pd.isna(price):
        return np.nan

    price = str(price).strip()

    if price == "Call for Price":
        return np.nan

    if "Lac" in price:
        num = float(price.replace("Lac", "").strip())
        return num * 100000

    price = price.replace(",", "")

    try:
        return float(price)
    except:
        return np.nan

In [18]:
df['Price'] = df['Price'].apply(clean_price)

In [19]:
df['Price'].sample(30)

14403     67000.0
16478     72000.0
2428      27500.0
5662     110000.0
7577     140000.0
18859     50000.0
3506     140000.0
22695     25000.0
11917    450000.0
2170       8000.0
193      310000.0
20503     65000.0
696       45100.0
21026     52000.0
1673      20000.0
17144     35000.0
7173     120000.0
830       20000.0
18260     15000.0
12583     47000.0
3317      55000.0
20439     28000.0
10666     95000.0
16476    150000.0
21209    330000.0
20311     85000.0
16877    100000.0
14814     65000.0
886      110000.0
11228     27000.0
Name: Price, dtype: float64

In [22]:
df['Area'].sample(30)

1973          None
18286     900 12800
16328     850 12800
22520     225 12800
14505     714 12800
11739    1000 12800
14632     975 12800
4878     1007 12800
14549     540 12800
21269     310 12800
20560    1570 12800
23326         None
11743     900 12800
8683     1475 12800
17821    3100 12800
5652      992 12800
6023     1230 12800
4266     1450 12800
12704     500 12800
17075    1040 12800
21182     994 12800
19504    3000 12800
14485    1000 12800
6352     1350 12800
5118     1000 12800
16966     700 12800
19994    1250 12800
7717     1366 12800
15349    1250 12800
8741      650 12800
Name: Area, dtype: object

In [23]:
df['Area'].head(20)

0      750 12800
1     1980 12800
2     1592 12800
3     1305 12800
4     1350 12800
5     2000 12800
6     2150 12800
7      737 12800
8      910 12800
9      700 12800
10    2100 12800
11    2120 12800
12    1475 12800
13     425 12800
14    1312 12800
15     695 12800
16    3450 12800
17    4300 12800
18    1000 12800
19     850 12800
Name: Area, dtype: object

In [30]:
import pandas as pd
import numpy as np

def clean_area(area):
    if pd.isna(area):
        return np.nan

    area = str(area).strip()

    if area.lower() == 'none':
        return np.nan

    try:
        return float(area.split()[0])
    except:
        return np.nan

In [31]:
df['Area'] = df['Area'].apply(clean_area)

In [26]:
df['Area'].isnull().sum()

np.int64(0)

In [32]:
df['Price_per_sqft'] = df['Price'] / df['Area']

In [28]:
df['Area'].dtype

dtype('O')

In [33]:
df[['Price','Area','Price_per_sqft']].sample(10)

          Price    Area  Price_per_sqft
3301    42000.0   700.0       60.000000
7013    78000.0     NaN             NaN
13044  140000.0  1580.0       88.607595
17016  110000.0  1400.0       78.571429
2231    18000.0  1200.0       15.000000
22240   22000.0   640.0       34.375000
5346   130000.0  1050.0      123.809524
4977   450000.0  2350.0      191.489362
10844   58000.0  1058.0       54.820416
22778   60000.0  1200.0       50.000000

In [35]:
print(df['BHK'].dtype)
print(df['Bathrooms'].dtype)
print(df['Balconies'].dtype)

object
object
object

In [34]:
df[['BHK','Bathrooms','Balconies']].sample(20)

       BHK Bathrooms Balconies
12975    2         2       NaN
4178     4         4         3
12921    2         2       NaN
1777     1         1         1
8897     2         2       NaN
245      2         2         3
11047    3         3       NaN
13041    4         4         4
5562     2         2       NaN
20163    2         2       NaN
14415    1         1       NaN
15430    4         4         2
16042    2         2       NaN
20851  NaN         2       NaN
14293    1         2       NaN
13790    2         2         1
16633    1         1       NaN
3191   NaN       NaN       NaN
20650    2         2         1
13199    3         2         1

In [36]:
df['Price_per_sqft'].describe()

count    22259.000000
mean        80.933982
std        223.403527
min          3.333333
25%         48.582996
50%         65.625000
75%         92.307692
max      16779.661017
Name: Price_per_sqft, dtype: float64

In [37]:
df[df.duplicated()].head()

,Title,Price,Area,BHK,Bathrooms,Furnished,Balconies,Floor,Facing,Amenities,Property Type,Year of Construction,Description,Price_per_sqft
997,1BHK Multistorey Apartment for Rent in Omkar M...,55000.0,700.0,1,1,Semi-Furnished,NaN,1,NaN,NaN,Apartment,NaN,"1 BHK, Multistorey Apartment is available for ...",78.571429
1380,1BHK Multistorey Apartment for Rent in Virar West,8500.0,675.0,1,2,Semi-Furnished,NaN,9,NaN,NaN,Apartment,NaN,"1 BHK, Multistorey Apartment is available for ...",12.592593
1802,1BHK Multistorey Apartment for Rent in Kanakia...,55000.0,555.0,1,2,Semi-Furnished,NaN,17,NaN,"Garden/Park, Pool",Apartment,NaN,"1 BHK, Multistorey Apartment is available for ...",99.099099
2004,1BHK Multistorey Apartment for Rent in Hill pa...,28000.0,550.0,1,1,Unfurnished,NaN,4,NaN,Garden/Park,Apartment,NaN,"1 BHK, Multistorey Apartment is available for ...",50.909091
2314,1BHK Residential House for Rent in Kandivali East,7000.0,200.0,1,1,Unfurnished,NaN,1,NaN,NaN,Residential House,NaN,"1 BHK, Residential House is available for Rent...",35.000000

In [39]:
df.to_csv('Mumbai_property_details_cleaned.csv', index=False)

In [40]:
from google.colab import files

files.download('Mumbai_property_details_cleaned.csv')